# Generated by Django 3.1.2 on 2020-10-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.IntegerField()),
                ('book_name', models.TextField()),
                ('btd', models.DateField()),
                ('bsd', models.DateField(blank=True, null=True)),
                ('uname', models.TextField()),
                ('uid', models.CharField(max_length=20)),
                ('fine', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
