# Generated by Django 3.1.2 on 2020-10-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201018_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
