# Generated by Django 3.1.2 on 2020-10-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_book_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_details',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
